summary : function
contents : 
  fnc-1 : show varsion
  fnc-2 : show help
  fnc-3 : 
    fnc-3-0 : generate routing source
    fnc-3-1 : 
      fnc-3-1-0 : check parameter 
      fnc-3-1-1 : target must exists directory path
      fnc-3-1-2 : output must exists directory path
      fnc-3-1-3 : default output is current
      fnc-3-1-4 : config must exists file path
    fnc-3-2 : read config
    fnc-3-3 : pre-check generate
    fnc-3-4 : generate controller
    fnc-3-5 : generate group
    
