summary  : command line interface
contents : 
  cmd-1    : 
    cmd-1-0  : target directory parameter
    cmd-1-1  : this parameter is no prefix
    cmd-1-2  : this parameter is require arguments
  cmd-2    : 
    cmd-2-0  : output destination directory path parameter
    cmd-2-1  : '-o' option
    cmd-2-2  : this option is require arguments
  cmd-3    :
    cmd-3-0  : config file path parameter
    cmd-3-1  : '-c' option
    cmd-3-2  : this option is require arguments
  cmd-4    : '-v' option
  cmd-5    : '-h' option
  cmd-6    : 
    cmd-6-0  : parameter syntax check
    cmd-6-1  : '-v' option specified single
    cmd-6-2  : '-h' option specified single
    cmd-6-3  : target directory is require parameter
    cmd-6-4  : show help if syntax error detected
  cmd-7    : '-l' option
  cmd-8    :
    cmd-8-0  : call front function
    cmd-8-1  : input target
    cmd-8-2  : input output
    cmd-8-3  : input config
    cmd-8-4  : input log
