summary  : generator
contents : 
  gen-1    :
    gen1-0   : pre-check generate
    gen-1-1  : check writeble output directory
    gen-1-2  : rename directory ,if there is already directory
  gen-1    : 
    gen-1-0  : generate route controller
    gen-1-1  : session route
    
  gen-2    : 
    gen-2-0  : generate route group
    gen-2-1  : url routes
    gen-2-2  : any route
    
